version: '3.8'
services:
  # Define the network function to be scaled
  skeleton:
    image: "ubuntu:20.04"
    volumes:
      - /local/onvm/openNetVM/container:/container
    hostname: 'skeleton'
    working_dir: /container
    command: /bin/bash -c "./test.sh"
