version: '3.8'
services:
  # Define the network function to be scaled
  skeleton:
    # Need to run Dockerfile to build this image
    image: "cont_nf_test:latest"
    volumes:
      # .Task.Slot is an auto-incrementing reference to the current container
      - /tmp/pipe/{{.Task.Slot}}:/pipe
    working_dir: /container
    command: ./cont_nf
