version: '3.8'
services:
  # Define the network function to be scaled
  skeleton:
    # build: .
    # image: "ubuntu:20.04"
    image: "cont_nf_test:latest"
    volumes:
      # - /home/kdeems/openNetVM/examples/api_gateway/scaler:/container
      - /tmp/rx/{{.Task.Slot}}:/rx_pipe
      - /tmp/tx/{{.Task.Slot}}:/tx_pipe
    working_dir: /container
    command: ./build/app/cont_nf
